# tasks when mariadb-centos ansible-role-dbmanage
---
- name: "Add yum repo file"
  template: src=mariadb_centos.repo.j2 dest=/etc/yum.repos.d/mariadb.repo owner=root group=root mode=0644

- name: "Install MariaDB from deb packadges"
  yum: name={{ item }} enablerepo=mariadb state=present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: "Install MySQLdb Python package for secure installations."
  yum: name=MySQL-python state=present
  when: secure_installation and mysql_root_password is defined
