# tasks when remote-mysql ansible-role-dbmanage
---
# implemented for Audiocodes with mysql-rds ... 
- debug: msg="Running in {{ db_mode }} on {{ db_flavor }}"

- name: 'make sure mysql libs are installed'
  yum: name=MySQL-python state=installed
  when: ansible_os_family == "RedHat"
  become: true

- name: "Create Database for appllicationi(s) iterrate over app_db_credentials"
  mysql_db: >
    name={{ item.app_database_name }}
    login_host={{ item.database_hostname }}
    login_password={{ database_admin_password }}
    login_user={{ database_admin_user  }}
    encoding={{ item.database_encoding }}
    state=present
  with_items: "{{ app_db_credentials }}"

- name: "Create users for application(s)"
  mysql_user: >
   host={{ansible_ssh_host}}
   login_host={{ item.database_hostname }}
   login_user={{ database_admin_user }}
   login_password={{ database_admin_password }}
   name={{ item.database_admin_user }}
   password={{ item.app_database_password }}
   priv={{ item.app_database_name }}.*:ALL
   state=present
  with_items: "{{ app_db_credentials }}"

- name: "Make sure we do not have unwanted users configured (with wrong access)"
  debug: "This in future will clean all root@'%' etc from {{ db_flavor }} - move this to {{ db_flavor }}-hardeninig.yml"

- name: "Set facts for app"
  include: artifactory.yml
  with_items: "{{ app_db_credentials }}"
  # will be removed in the future once all apps are in place and we can say {{ item.app_name }}.yml
  when: item.app_name == "artifactory"
  
